### ISSUE TITLE
Can this script download the latest version of GraalVM enterprise?

### ISSUE THREAD

**Issue by TechPro424** [he3als/graalvm-downloader#1]
Can this script download the latest version of GraalVM enterprise?

**Comment by he3als** [comment]
It only gets non-CE versions.

It will always get the latest versions of either GraalVM Enterprise or Oracle GraalVM

For Java 17 and 20, GraalVM Enterprise and the new Oracle GraalVM version under an Oracle license are the same thing.

**Comment by he3als** [comment]
https://github.com/he3als/graalvm-downloader/releases/tag/v1.0.1

Sorry, I realised that the script was getting the oldest version of GraalVM Java 8 instead of the latest. That's fixed in v1.0.1.
